# Generated by Django 3.0.6 on 2020-05-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fcusers',
            table='fastcmapus_fcusers',
        ),
    ]
