# Generated by Django 3.0.6 on 2020-05-29 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcusers', '0002_auto_20200529_2315'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fcusers',
            table='fastcampus_fcusers',
        ),
    ]
